version: "3.8"

services: 
  app:
    build: .
    container_name: car_rental
    ports:
      - 3333:3333
      - 9229:9229 
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite

  database_ignite: 
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=car_rental
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local